services:

  Markocupic\RszLageranmeldungBundle\EventListener\ContaoHooks\ParseBackendTemplateListener:
    tags:
      - { name: contao.hook, hook: parseBackendTemplate, method: addDownloadButton, priority: 0 }

  Markocupic\RszLageranmeldungBundle\EventListener\ContaoHooks\LoadFormFieldListener:
    tags:
      - { name: contao.hook, hook: loadFormField, method: loadFormField, priority: 0 }

  Markocupic\RszLageranmeldungBundle\EventListener\ContaoHooks\ProcessFormDataListener:
    tags:
      - { name: contao.hook, hook: processFormData, method: processFormData, priority: 0 }