services:

  Markocupic\RszJahresprogrammBundle\EventListener\ContaoHooks\ParseBackendTemplateListener:
    tags:
      - { name: contao.hook, hook: parseBackendTemplate, method: addDownloadButton, priority: 0 }